export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST'
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS'
export const GET_MESSAGE_ERROR = 'GET_MESSAGE_ERROR'

export const ADD_MESSAGE_REQUEST = 'ADD_MESSAGE_REQUEST'
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS'
export const ADD_MESSAGE_ERROR = 'ADD_MESSAGE_ERROR'